mainData = [
	{
		id: 1,
		type: "Wedding",
		src: "img/gallery/1.jpg",
		tum: "img/gallery/1.jpg",
		cp:
			"“Gravitation is not responsible for people falling in love.” —Albert Einstein",
	},
	{
		id: 2,
		type: "Wedding",
		src: "img/gallery/2.jpg",
		tum: "img/gallery/2.jpg",
		cp:
			"You know you're in love when you can't fall asleep because reality is finally better than your dreams. —Dr. Seuss",
	},
	{
		id: 3,
		type: "Wedding",
		src: "img/gallery/3.jpg",
		tum: "img/gallery/3.jpg",
		cp:
			"“We may not have it all together but, together we have it all.” -Anonymous",
	},
	{
		id: 4,
		type: "Wedding",
		src: "img/gallery/4.jpg",
		tum: "img/gallery/4.jpg",
		cp:
			"“Berhentilah bertanya bagaimana menemukan pasangan yang baik. Mulailah menjadi orang yang baik dan terus lebih baik, maka akan terjawab sendiri pertanyaan ini” - Tere Liye",
	},
	// {
	// 	id: 5,
	// 	type: "Wedding",
	// 	src: "img/gallery/5.jpg",
	// 	tum: "img/gallery/5.jpg",
	// 	cp: "“There is no such cozy combination as man and wife.” – Menander",
	// },
	{
		id: 6,
		type: "Design",
		src: "img/gallery/6.jpg",
		tum: "img/gallery/6.jpg",
		cp:
			"Hanya ada satu kata agar rakyat Indonesia hidup dalam keadilan dan kesejahteraan, apa itu?",
	},
	{
		id: 7,
		type: "Design",
		src: "img/gallery/7.jpg",
		tum: "img/gallery/7.jpg",
		cp: "Edit challenge",
	},
	// {
	// 	id: 8,
	// 	type: "Design",
	// 	src: "img/gallery/8.jpg",
	// 	tum: "img/gallery/8.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 9,
	// 	type: "Design",
	// 	src: "img/gallery/9.jpg",
	// 	tum: "img/gallery/9.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 10,
	// 	type: "Design",
	// 	src: "img/gallery/10.jpg",
	// 	tum: "img/gallery/10.jpg",
	// 	cp: "Nice Photo",
	// },
	{
		id: 11,
		type: "Graduation",
		src: "img/gallery/11.jpg",
		tum: "img/gallery/11.jpg",
		cp: "IPB University",
	},
	{
		id: 12,
		type: "Graduation",
		src: "img/gallery/12.jpg",
		tum: "img/gallery/12.jpg",
		cp: "IPB University",
	},
	{
		id: 13,
		type: "Graduation",
		src: "img/gallery/13.jpg",
		tum: "img/gallery/13.jpg",
		cp: "IPB University",
	},
	{
		id: 14,
		type: "Graduation",
		src: "img/gallery/14.jpg",
		tum: "img/gallery/14.jpg",
		cp: "IPB University",
	},
	{
		id: 15,
		type: "Graduation",
		src: "img/gallery/15.jpg",
		tum: "img/gallery/15.jpg",
		cp: "IPB Universityo",
	},
	{
		id: 16,
		type: "Event",
		src: "img/gallery/16.jpg",
		tum: "img/gallery/16.jpg",
		cp: "Sendi sehat semangat gowes ya, aminnn",
	},
	{
		id: 17,
		type: "Event",
		src: "img/gallery/17.jpg",
		tum: "img/gallery/17.jpg",
		cp: "Dipotoin kepin",
	},
	{
		id: 18,
		type: "Event",
		src: "img/gallery/18.jpg",
		tum: "img/gallery/18.jpg",
		cp: "Nice Photo",
	},
	{
		id: 19,
		type: "Event",
		src: "img/gallery/19.jpg",
		tum: "img/gallery/19.jpg",
		cp: "Nice Photo",
	},
	{
		id: 20,
		type: "Event",
		src: "img/gallery/20.jpg",
		tum: "img/gallery/20.jpg",
		cp: "Nice Photo",
	},
	// {
	// 	id: 21,
	// 	type: "Wedding",
	// 	src: "img/gallery/21.jpg",
	// 	tum: "img/gallery/21.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 22,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 23,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 24,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 25,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 26,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 27,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 28,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 29,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
	// {
	// 	id: 30,
	// 	type: "Wedding",
	// 	src: "img/gallery/22.jpg",
	// 	tum: "img/gallery/22.jpg",
	// 	cp: "Nice Photo",
	// },
];
